import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import NextProvider from "./provider";

const myAppFont = Nunito({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={myAppFont.className} suppressHydrationWarning={true}>
        <NextProvider>{children}</NextProvider>
      </body>
    </html>
  );
}
